# Generated by Django 4.1.5 on 2023-03-20 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="название проекта"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание проекта"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания проекта"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="время обновления проекта"
                    ),
                ),
                (
                    "finish_date",
                    models.DateTimeField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="завершить проект до",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="завершён ли проект"
                    ),
                ),
                (
                    "complete_date",
                    models.DateTimeField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="время завершения проекта",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор проекта",
                    ),
                ),
                (
                    "author_update",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proj_author_update",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто изменил проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="название спринта"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание спринта"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания спринта"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="время обновления спринта"
                    ),
                ),
                (
                    "finish_date",
                    models.DateTimeField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="завершить спринт до",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="завершён ли спринт"
                    ),
                ),
                (
                    "complete_date",
                    models.DateTimeField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="время завершения спринта",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор спринта",
                    ),
                ),
                (
                    "author_update",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprint_author_update",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто изменил спринт",
                    ),
                ),
                (
                    "proj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ziralist.project",
                        verbose_name="название проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спринт",
                "verbose_name_plural": "Спринты",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="название статуса"),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания статуса"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="время изменения статуса"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор статуса",
                    ),
                ),
                (
                    "proj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ziralist.project",
                        verbose_name="название проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="название задачи"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание задачи"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания задачи"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="время обновления задачи"
                    ),
                ),
                (
                    "finish_date",
                    models.DateTimeField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="завершить задачу до",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="завершёна ли задача"
                    ),
                ),
                (
                    "complete_date",
                    models.DateTimeField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="время завершения задачи",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор задачи",
                    ),
                ),
                (
                    "author_update",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_author_update",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто изменил задачу",
                    ),
                ),
                (
                    "proj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="ziralist.project",
                        verbose_name="название проекта",
                    ),
                ),
                (
                    "spr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprints",
                        to="ziralist.sprint",
                        verbose_name="название спринта",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        default="Только создана",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ziralist.status",
                        verbose_name="статус задачи",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="исполнитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["id"],
            },
        ),
    ]
